import type { Page, Plugin } from "@vuepress/core";
import type { LocaleConfig } from "@vuepress/shared";
import * as chokidar from "chokidar";
import { prepareSearchIndex } from "./prepareSearchIndex";

export interface SearchPluginOptions {
  locales?: LocaleConfig<{
    placeholder: string;
  }>;
  hotKeys: string[];
  maxSuggestions: number;
  isSearchable: (page: Page) => boolean;
  getExtraFields: (page: Page) => string[];
}

export const searchPlugin: Plugin<SearchPluginOptions> = (
  {
    locales = {},
    hotKeys = ["s", "/"],
    maxSuggestions = 5,
    isSearchable = () => true,
    getExtraFields = () => []
  },
  app
) => {
  if (app.options.bundler.endsWith("vite")) {
    // eslint-disable-next-line import/no-extraneous-dependencies
    app.options.bundlerConfig.viteOptions = require("vite").mergeConfig(
      app.options.bundlerConfig.viteOptions,
      {
        optimizeDeps: {
          exclude: ["@renovamen/vuepress-plugin-search"]
        }
      }
    );
  }

  return {
    name: "@renovamen/vuepress-plugin-search",

    onPrepared: (app) =>
      prepareSearchIndex({ app, isSearchable, getExtraFields }),

    onWatched: (app, watchers) => {
      // here we only watch the page data files
      // if the extra fields generated by `getExtraFields` are not included
      // in the page data, the changes may not be watched
      const searchIndexWatcher = chokidar.watch("internal/pageData/*", {
        cwd: app.dir.temp(),
        ignoreInitial: true
      });
      searchIndexWatcher.on("add", () => {
        prepareSearchIndex({ app, isSearchable, getExtraFields });
      });
      searchIndexWatcher.on("change", () => {
        prepareSearchIndex({ app, isSearchable, getExtraFields });
      });
      searchIndexWatcher.on("unlink", () => {
        prepareSearchIndex({ app, isSearchable, getExtraFields });
      });
      watchers.push(searchIndexWatcher);
    }
  };
};
